# Generated by Django 4.2.3 on 2023-08-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_keyboard_product_type_keycap_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='keycap',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='pcb',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='product_type',
        ),
    ]
